version: '2'
services:
  zookeeper:
    image: 31z4/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zk1/data:/data
      - ./zk1/datalog:/datalog
  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./kafka1/data:/var/lib/kafka/data  